/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateTranscriptionsListtranscriptionInputBuilder {
    //the instance to build
    private CreateTranscriptionsListtranscriptionInput createTranscriptionsListtranscriptionInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateTranscriptionsListtranscriptionInputBuilder() {
        createTranscriptionsListtranscriptionInput = new CreateTranscriptionsListtranscriptionInput();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public CreateTranscriptionsListtranscriptionInputBuilder page(Integer page) {
        createTranscriptionsListtranscriptionInput.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public CreateTranscriptionsListtranscriptionInputBuilder pagesize(Integer pagesize) {
        createTranscriptionsListtranscriptionInput.setPagesize(pagesize);
        return this;
    }

    /**
     * The state of the transcription.
     */
    public CreateTranscriptionsListtranscriptionInputBuilder status(StatusEnum status) {
        createTranscriptionsListtranscriptionInput.setStatus(status);
        return this;
    }

    /**
     * The date the transcription took place.
     */
    public CreateTranscriptionsListtranscriptionInputBuilder dateTranscribed(String dateTranscribed) {
        createTranscriptionsListtranscriptionInput.setDateTranscribed(dateTranscribed);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateTranscriptionsListtranscriptionInput build() {
        return createTranscriptionsListtranscriptionInput;
    }
}