/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateIncomingphoneListnumberInput 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5193049757641750680L;
    private Integer page = 1;
    private Integer pageSize = 10;
    private Numbertype16Enum numberType;
    private String friendlyName;
    /** GETTER
     * Which page of the overall response will be returned. Page indexing starts at 1.
     */
    @JsonGetter("Page")
    public Integer getPage ( ) { 
        return this.page;
    }
    
    /** SETTER
     * Which page of the overall response will be returned. Page indexing starts at 1.
     */
    @JsonSetter("Page")
    public void setPage (Integer value) { 
        this.page = value;
    }
 
    /** GETTER
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    @JsonGetter("PageSize")
    public Integer getPageSize ( ) { 
        return this.pageSize;
    }
    
    /** SETTER
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    @JsonSetter("PageSize")
    public void setPageSize (Integer value) { 
        this.pageSize = value;
    }
 
    /** GETTER
     * The capability supported by the number.Number type either SMS,Voice or all
     */
    @JsonGetter("NumberType")
    public Numbertype16Enum getNumberType ( ) { 
        return this.numberType;
    }
    
    /** SETTER
     * The capability supported by the number.Number type either SMS,Voice or all
     */
    @JsonSetter("NumberType")
    public void setNumberType (Numbertype16Enum value) { 
        this.numberType = value;
    }
 
    /** GETTER
     * A human-readable label added to the number object.
     */
    @JsonGetter("FriendlyName")
    public String getFriendlyName ( ) { 
        return this.friendlyName;
    }
    
    /** SETTER
     * A human-readable label added to the number object.
     */
    @JsonSetter("FriendlyName")
    public void setFriendlyName (String value) { 
        this.friendlyName = value;
    }
 
}
 