/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateEmailListspamemailInputBuilder {
    //the instance to build
    private CreateEmailListspamemailInput createEmailListspamemailInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateEmailListspamemailInputBuilder() {
        createEmailListspamemailInput = new CreateEmailListspamemailInput();
    }

    /**
     * The starting point of the list of spam emails that should be returned.
     */
    public CreateEmailListspamemailInputBuilder offset(String offset) {
        createEmailListspamemailInput.setOffset(offset);
        return this;
    }

    /**
     * The count of results that should be returned.
     */
    public CreateEmailListspamemailInputBuilder limit(String limit) {
        createEmailListspamemailInput.setLimit(limit);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateEmailListspamemailInput build() {
        return createEmailListspamemailInput;
    }
}