/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateDedicatedshortcodeUpdateshortcodeInputBuilder {
    //the instance to build
    private CreateDedicatedshortcodeUpdateshortcodeInput createDedicatedshortcodeUpdateshortcodeInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateDedicatedshortcodeUpdateshortcodeInputBuilder() {
        createDedicatedshortcodeUpdateshortcodeInput = new CreateDedicatedshortcodeUpdateshortcodeInput();
    }

    /**
     * List of valid dedicated shortcode to your Ytel account.
     */
    public CreateDedicatedshortcodeUpdateshortcodeInputBuilder shortcode(String shortcode) {
        createDedicatedshortcodeUpdateshortcodeInput.setShortcode(shortcode);
        return this;
    }

    /**
     * User generated name of the dedicated shortcode.
     */
    public CreateDedicatedshortcodeUpdateshortcodeInputBuilder friendlyName(String friendlyName) {
        createDedicatedshortcodeUpdateshortcodeInput.setFriendlyName(friendlyName);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.
     */
    public CreateDedicatedshortcodeUpdateshortcodeInputBuilder callbackMethod(String callbackMethod) {
        createDedicatedshortcodeUpdateshortcodeInput.setCallbackMethod(callbackMethod);
        return this;
    }

    /**
     * URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
     */
    public CreateDedicatedshortcodeUpdateshortcodeInputBuilder callbackUrl(String callbackUrl) {
        createDedicatedshortcodeUpdateshortcodeInput.setCallbackUrl(callbackUrl);
        return this;
    }

    /**
     * Specifies the HTTP method used to request the required FallbackUrl once call connects.
     */
    public CreateDedicatedshortcodeUpdateshortcodeInputBuilder fallbackMethod(String fallbackMethod) {
        createDedicatedshortcodeUpdateshortcodeInput.setFallbackMethod(fallbackMethod);
        return this;
    }

    /**
     * URL used if any errors occur during execution of InboundXML or at initial request of the required Url provided with the POST.
     */
    public CreateDedicatedshortcodeUpdateshortcodeInputBuilder fallbackUrl(String fallbackUrl) {
        createDedicatedshortcodeUpdateshortcodeInput.setFallbackUrl(fallbackUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateDedicatedshortcodeUpdateshortcodeInput build() {
        return createDedicatedshortcodeUpdateshortcodeInput;
    }
}