/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateIncomingphoneAvailablenumberInputBuilder {
    //the instance to build
    private CreateIncomingphoneAvailablenumberInput createIncomingphoneAvailablenumberInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateIncomingphoneAvailablenumberInputBuilder() {
        createIncomingphoneAvailablenumberInput = new CreateIncomingphoneAvailablenumberInput();
    }

    /**
     * Number type either SMS,Voice or all
     */
    public CreateIncomingphoneAvailablenumberInputBuilder numbertype(Numbertype16Enum numbertype) {
        createIncomingphoneAvailablenumberInput.setNumbertype(numbertype);
        return this;
    }

    /**
     * Specifies the area code for the returned list of available numbers. Only available for North American numbers.
     */
    public CreateIncomingphoneAvailablenumberInputBuilder areacode(String areacode) {
        createIncomingphoneAvailablenumberInput.setAreacode(areacode);
        return this;
    }

    /**
     * The count of objects to return.
     */
    public CreateIncomingphoneAvailablenumberInputBuilder pagesize(Integer pagesize) {
        createIncomingphoneAvailablenumberInput.setPagesize(pagesize);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateIncomingphoneAvailablenumberInput build() {
        return createIncomingphoneAvailablenumberInput;
    }
}