/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateUsageListusageInputBuilder {
    //the instance to build
    private CreateUsageListusageInput createUsageListusageInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateUsageListusageInputBuilder() {
        createUsageListusageInput = new CreateUsageListusageInput();
    }

    /**
     * Filter usage results by product type.
     */
    public CreateUsageListusageInputBuilder productCode(ProductCode27Enum productCode) {
        createUsageListusageInput.setProductCode(productCode);
        return this;
    }

    /**
     * Filter usage objects by start date.
     */
    public CreateUsageListusageInputBuilder startDate(String startDate) {
        createUsageListusageInput.setStartDate(startDate);
        return this;
    }

    /**
     * Filter usage objects by end date.
     */
    public CreateUsageListusageInputBuilder endDate(String endDate) {
        createUsageListusageInput.setEndDate(endDate);
        return this;
    }

    /**
     * Will include all subaccount usage data
     */
    public CreateUsageListusageInputBuilder includeSubAccounts(String includeSubAccounts) {
        createUsageListusageInput.setIncludeSubAccounts(includeSubAccounts);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateUsageListusageInput build() {
        return createUsageListusageInput;
    }
}