/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateIncomingphoneBulkbuyInputBuilder {
    //the instance to build
    private CreateIncomingphoneBulkbuyInput createIncomingphoneBulkbuyInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateIncomingphoneBulkbuyInputBuilder() {
        createIncomingphoneBulkbuyInput = new CreateIncomingphoneBulkbuyInput();
    }

    /**
     * The capability the number supports.
     */
    public CreateIncomingphoneBulkbuyInputBuilder numberType(Numbertype16Enum numberType) {
        createIncomingphoneBulkbuyInput.setNumberType(numberType);
        return this;
    }

    /**
     * Specifies the area code for the returned list of available numbers. Only available for North American numbers.
     */
    public CreateIncomingphoneBulkbuyInputBuilder areaCode(String areaCode) {
        createIncomingphoneBulkbuyInput.setAreaCode(areaCode);
        return this;
    }

    /**
     * A positive integer that tells how many number you want to buy at a time.
     */
    public CreateIncomingphoneBulkbuyInputBuilder quantity(String quantity) {
        createIncomingphoneBulkbuyInput.setQuantity(quantity);
        return this;
    }

    /**
     * If desired quantity is unavailable purchase what is available .
     */
    public CreateIncomingphoneBulkbuyInputBuilder leftover(String leftover) {
        createIncomingphoneBulkbuyInput.setLeftover(leftover);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateIncomingphoneBulkbuyInput build() {
        return createIncomingphoneBulkbuyInput;
    }
}