/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateUserDeletesubaccountInputBuilder {
    //the instance to build
    private CreateUserDeletesubaccountInput createUserDeletesubaccountInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateUserDeletesubaccountInputBuilder() {
        createUserDeletesubaccountInput = new CreateUserDeletesubaccountInput();
    }

    /**
     * The SubaccountSid to be deleted
     */
    public CreateUserDeletesubaccountInputBuilder subAccountSID(String subAccountSID) {
        createUserDeletesubaccountInput.setSubAccountSID(subAccountSID);
        return this;
    }

    /**
     * 0 to delete or 1 to merge numbers to parent account.
     */
    public CreateUserDeletesubaccountInputBuilder mergeNumber(MergeNumberEnum mergeNumber) {
        createUserDeletesubaccountInput.setMergeNumber(mergeNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateUserDeletesubaccountInput build() {
        return createUserDeletesubaccountInput;
    }
}