/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateLetterListsletterInputBuilder {
    //the instance to build
    private CreateLetterListsletterInput createLetterListsletterInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateLetterListsletterInputBuilder() {
        createLetterListsletterInput = new CreateLetterListsletterInput();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public CreateLetterListsletterInputBuilder page(Integer page) {
        createLetterListsletterInput.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public CreateLetterListsletterInputBuilder pagesize(Integer pagesize) {
        createLetterListsletterInput.setPagesize(pagesize);
        return this;
    }

    /**
     * The unique identifier for a letter object.
     */
    public CreateLetterListsletterInputBuilder lettersid(String lettersid) {
        createLetterListsletterInput.setLettersid(lettersid);
        return this;
    }

    /**
     * The date the letter was created.
     */
    public CreateLetterListsletterInputBuilder dateCreated(String dateCreated) {
        createLetterListsletterInput.setDateCreated(dateCreated);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateLetterListsletterInput build() {
        return createLetterListsletterInput;
    }
}