/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateUserSubaccountactivationInput 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5610084016064004986L;
    private String subAccountSID;
    private MActivateEnum mActivate;
    /** GETTER
     * The SubaccountSid to be activated or suspended
     */
    @JsonGetter("SubAccountSID")
    public String getSubAccountSID ( ) { 
        return this.subAccountSID;
    }
    
    /** SETTER
     * The SubaccountSid to be activated or suspended
     */
    @JsonSetter("SubAccountSID")
    public void setSubAccountSID (String value) { 
        this.subAccountSID = value;
    }
 
    /** GETTER
     * 0 to suspend or 1 to activate
     */
    @JsonGetter("mActivate")
    public MActivateEnum getMActivate ( ) { 
        return this.mActivate;
    }
    
    /** SETTER
     * 0 to suspend or 1 to activate
     */
    @JsonSetter("mActivate")
    public void setMActivate (MActivateEnum value) { 
        this.mActivate = value;
    }
 
}
 