/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class CreateCarrierLookuplistInputBuilder {
    //the instance to build
    private CreateCarrierLookuplistInput createCarrierLookuplistInput;

    /**
     * Default constructor to initialize the instance
     */
    public CreateCarrierLookuplistInputBuilder() {
        createCarrierLookuplistInput = new CreateCarrierLookuplistInput();
    }

    /**
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    public CreateCarrierLookuplistInputBuilder page(Integer page) {
        createCarrierLookuplistInput.setPage(page);
        return this;
    }

    /**
     * The count of objects to return per page.
     */
    public CreateCarrierLookuplistInputBuilder pageSize(Integer pageSize) {
        createCarrierLookuplistInput.setPageSize(pageSize);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateCarrierLookuplistInput build() {
        return createCarrierLookuplistInput;
    }
}