/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;

public class PostcardCreatepostcardInputBuilder {
    //the instance to build
    private PostcardCreatepostcardInput postcardCreatepostcardInput;

    /**
     * Default constructor to initialize the instance
     */
    public PostcardCreatepostcardInputBuilder() {
        postcardCreatepostcardInput = new PostcardCreatepostcardInput();
    }

    /**
     * The AddressId or an object structured when creating an address by addresses/Create.
     */
    public PostcardCreatepostcardInputBuilder to(String to) {
        postcardCreatepostcardInput.setTo(to);
        return this;
    }

    /**
     * The AddressId or an object structured when creating an address by addresses/Create.
     */
    public PostcardCreatepostcardInputBuilder from(String from) {
        postcardCreatepostcardInput.setFrom(from);
        return this;
    }

    /**
     * Set an existing postcard by attaching its PostcardId.
     */
    public PostcardCreatepostcardInputBuilder attachbyid(String attachbyid) {
        postcardCreatepostcardInput.setAttachbyid(attachbyid);
        return this;
    }

    /**
     * A 4.25"x6.25" or 6.25"x11.25" image to use as the front of the postcard.  This can be a URL, local file, or an HTML string. Supported file types are PDF, PNG, and JPEG.
     */
    public PostcardCreatepostcardInputBuilder front(String front) {
        postcardCreatepostcardInput.setFront(front);
        return this;
    }

    /**
     * A 4.25"x6.25" or 6.25"x11.25" image to use as the back of the postcard, supplied as a URL, local file, or HTML string.  This allows you to customize your back design, but we will still insert the recipient address for you.
     */
    public PostcardCreatepostcardInputBuilder back(String back) {
        postcardCreatepostcardInput.setBack(back);
        return this;
    }

    /**
     * The message for the back of the postcard with a maximum of 350 characters.
     */
    public PostcardCreatepostcardInputBuilder message(String message) {
        postcardCreatepostcardInput.setMessage(message);
        return this;
    }

    /**
     * Code for the dimensions of the media to be printed.
     */
    public PostcardCreatepostcardInputBuilder setting(String setting) {
        postcardCreatepostcardInput.setSetting(setting);
        return this;
    }

    /**
     * A description for the postcard.
     */
    public PostcardCreatepostcardInputBuilder description(String description) {
        postcardCreatepostcardInput.setDescription(description);
        return this;
    }

    /**
     * A string value that contains HTML markup.
     */
    public PostcardCreatepostcardInputBuilder htmldata(String htmldata) {
        postcardCreatepostcardInput.setHtmldata(htmldata);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PostcardCreatepostcardInput build() {
        return postcardCreatepostcardInput;
    }
}