/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.ytel.api.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import com.ytel.api.models.*;
import com.ytel.api.exceptions.*;
import com.ytel.api.APIHelper;
import com.ytel.api.Configuration;
import com.ytel.api.testing.TestHelper;
import com.ytel.api.controllers.EmailController;

import com.fasterxml.jackson.core.type.TypeReference;

public class EmailControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static EmailController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getEmail();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Retrieve a list of emails that have been blocked.
     * @throws Throwable
     */
    @Test
    public void testTestBlockedEmails() throws Throwable {
        // Parameters for the API call
        String offset = null;
        String limit = null;

        // Set callback and perform API call
        String result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.createBlockedEmails(offset, limit);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Retrieve a list of emails that are on the spam list.
     * @throws Throwable
     */
    @Test
    public void testTestSpamEmails() throws Throwable {
        // Parameters for the API call
        String offset = null;
        String limit = null;

        // Set callback and perform API call
        String result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.createSpamEmails(offset, limit);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Retrieve a list of emails that have bounced.
     * @throws Throwable
     */
    @Test
    public void testTestBouncedEmails() throws Throwable {
        // Parameters for the API call
        String offset = null;
        String limit = null;

        // Set callback and perform API call
        String result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.createBouncedEmails(offset, limit);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Retrieve a list of invalid email addresses.
     * @throws Throwable
     */
    @Test
    public void testTestInvalidEmails() throws Throwable {
        // Parameters for the API call
        String offset = null;
        String limit = null;

        // Set callback and perform API call
        String result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.createInvalidEmails(offset, limit);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Retrieve a list of email addresses from the unsubscribe list.
     * @throws Throwable
     */
    @Test
    public void testTestListUnsubscribedEmails() throws Throwable {
        // Parameters for the API call
        String offset = null;
        String limit = null;

        // Set callback and perform API call
        String result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.createListUnsubscribedEmails(offset, limit);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
